### ISSUE TITLE
[Feature] Add ability to sell custom amount

### ISSUE THREAD

**Issue by TaylorHe** [PhillipDiCarlo/corpaStocks.italiandogs#12]
Maybe add the ability to buy/sell certain amounts instead of always buying and selling 1 cent.

**Comment by PhillipDiCarlo** [comment]
This shouldn't be necessary as the streamers "IPO" value is formulated based off of their channel followers.

**Comment by PhillipDiCarlo** [comment]
After further thought. This feature won't be added as it will cause a user to be able to bring a streamer to a 0 score.
